Process Process-2:
Process Process-1:
Traceback (most recent call last):
  File "/home/carrusk/anaconda3/envs/beavr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/carrusk/anaconda3/envs/beavr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/initializers.py", line 36, in _start_component
    component = RealsenseCamera(
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/sensors/realsense.py", line 39, in __init__
    self._start_realsense(self._cam_serial_num)
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/sensors/realsense.py", line 63, in _start_realsense
    cfg = self.pipeline.start(config)
RuntimeError: No device connected
Traceback (most recent call last):
  File "/home/carrusk/anaconda3/envs/beavr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/carrusk/anaconda3/envs/beavr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/initializers.py", line 36, in _start_component
    component = RealsenseCamera(
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/sensors/realsense.py", line 39, in __init__
    self._start_realsense(self._cam_serial_num)
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/sensors/realsense.py", line 63, in _start_realsense
    cfg = self.pipeline.start(config)
RuntimeError: No device connected
tcp://10.31.130.1:10006
tcp://10.31.130.1:11006
tcp://10.31.130.1:10005
tcp://10.31.130.1:11005
Process Process-3:
Traceback (most recent call last):
  File "/home/carrusk/anaconda3/envs/beavr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/carrusk/anaconda3/envs/beavr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/initializers.py", line 36, in _start_component
    component = RealsenseCamera(
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/sensors/realsense.py", line 39, in __init__
    self._start_realsense(self._cam_serial_num)
  File "/home/carrusk/Documents/MIT/beavr-bot/src/beavr/components/sensors/realsense.py", line 63, in _start_realsense
    cfg = self.pipeline.start(config)
RuntimeError: No device connected
tcp://10.31.130.1:10007
tcp://10.31.130.1:11007
